### ISSUE TITLE
Filter on column doesn't change width correctly

### ISSUE THREAD

**Issue by OliverKK** [GuillaumeJasmin/react-table-hoc-fixed-columns#1]
Hi,
we are currently integrating/testing your HOC.
If filter is activated on a column the filter input does not change the width according to the column width.
Do you have an idea?

**Comment by GuillaumeJasmin** [comment]
Hi Oliver,
Thanks for your feedback ! Yes, the filters support was never test before, and it was completely broken.

I fixed it now and it works in `v0.1.3`
And I added it to the demo: https://guillaumejasmin.github.io/react-table-hoc-fixed-columns/

**Comment by OliverKK** [comment]
Hi @GuillaumeJasmin,
thanks for the very fast fix :)
I had to build local by using `npm pack`. v0.1.3 is not available at npm at the moment.

The filter inputs are perfectly aligned now.

Great job :+1:

**Comment by GuillaumeJasmin** [comment]
Hi,
It's strange, I published it yesterday just after the fix, and `v0.1.3` seems avaiable on npm: https://www.npmjs.com/package/react-table-hoc-fixed-columns .
You are not able to install it after change the version in your `package.json` ?

**Comment by OliverKK** [comment]
Hi,
this was my falt!
I have bin doing this: _"react-table-hoc-fixed-columns": "v0.1.3"_ instead of 
 _"react-table-hoc-fixed-columns": "0.1.3"_

Works like expected!
