### ISSUE TITLE
Enhancement: Typescript support

### ISSUE THREAD

**Issue by omkar-joshi** [GuillaumeJasmin/react-table-hoc-fixed-columns#15]
Hi,

Thank you so much for this HOC.
We are integrating it into our app. And we use React with Typescript. For TS support, I have added ambient declarations in the code. But it would be great if the types are shipped with the package itself.

Let me know your take on this. I'm happy to submit a PR.

**Comment by GuillaumeJasmin** [comment]
Hi,

Thanks for your proposal.
I didn't yet work with TS. On my react projects, I use Flow.
I don't know if TS is better than Flow for a open source project on React ? Flow seems to be more used on a React project than TS. But I haven't a fixed idea on that.

**Comment by Kepro** [comment]
@GuillaumeJasmin TS has much better support than Flow, and it's much better for sure...

**Comment by GuillaumeJasmin** [comment]
@Kepro I agree that TS has much better support. I recently start a migration from Flow to TS on one of my projects.

@omkar-joshi feel free to make a PR with TS support

**Comment by juliazxu** [comment]
@omkar-joshi Please add TS support!!! Much appreciated. 🐶🐶🐶

**Comment by omkar-joshi** [comment]
@juliazxu @GuillaumeJasmin On it. Shall put up a PR in a week

**Comment by NikhilMalagi** [comment]
HI @omkar-joshi, It would be really great to know if the TS support has been added.

Thanks

**Comment by papaiatis** [comment]
Hi @omkar-joshi , I'm also looking forward for the TS support. 
Any plans to do it in the near future?

Thanks!

**Comment by GuillaumeJasmin** [comment]
I just release a beta of typescript support.
You can try it with `react-table-hoc-fixed-columns@2.2.0-beta.1`

Please let me know how it works for you, if there is any breaking changes with typing.

**Comment by omkar-joshi** [comment]
@GuillaumeJasmin Sorry I couldn't make further progress on this. I was stuck up with some priority work. Apologies! Is there anything I can still help with?

**Comment by GuillaumeJasmin** [comment]
@omkar-joshi no problem ! :) 
You could try my version of typescript support if you have time and make feedback if it works for you

**Comment by GuillaumeJasmin** [comment]
included in latest release `v2.3.0`
