### ISSUE TITLE
important styles

### ISSUE THREAD

**Issue by serhiiZv** [GuillaumeJasmin/react-table-hoc-fixed-columns#16]
I think you should not use styles with important. 
I got an example where I cannot redefine it styles. 
Native React Table has props for style configuration through field  'styles' but we can not use the style with important since this will not work

`
styles: {
borderColor : "red!important"
}
`

**Comment by GuillaumeJasmin** [comment]
Hi,
Thanks for your feedback. There is few updates needed around style, like remove css-in-js to make possible better override with simple className, remove !important, etc. So I will improve style in few release, and your issue will be fixed

**Comment by GuillaumeJasmin** [comment]
I released a [v2 beta](https://github.com/GuillaumeJasmin/react-table-hoc-fixed-columns/releases/tag/v2.0.0-beta.1) , that should fix your issue.

Feel free to test it and make feedbacks :)
