### ISSUE TITLE
Horizontal scroll issue

### ISSUE THREAD

**Issue by vjekooo** [GuillaumeJasmin/react-table-hoc-fixed-columns#2]
When there's a horizontal scroll and you change number of rows from 5 to any of the bigger ones you get this UI issue. Moving the horizontal bar afterwards gets the issue fixed. 

[Image](https://imgur.com/a/5dSi5Gu)

**Comment by OliverKK** [comment]
Hello @GuillaumeJasmin ,
we are facing the same issue.

Could you dive into this? Would be awesome :+1: 

Regards Oliver

**Comment by GuillaumeJasmin** [comment]
Thanks for your feedback. It's fixed on `v0.1.5`

**Comment by vjekooo** [comment]
Awesome, thanx

**Comment by UPradeep** [comment]
Hi GuillaumeJasmin,
     we tried this example and it's working only if we have table without child table.Can we have an example with child table? Example screenshot.
![image](https://user-images.githubusercontent.com/16219117/43341528-cc9ba942-91ad-11e8-87ad-190930e42a9a.png)

**Comment by GuillaumeJasmin** [comment]
Hi,
Thanks for your feedback !
Have you tried `v1` beta ? Maybe it will fix your bug.
https://github.com/GuillaumeJasmin/react-table-hoc-fixed-columns/releases/tag/v1.0.0-beta.3

If you are on `v1` beta, please reproduce the bug on codesanbox, from this example: https://codesandbox.io/s/jnjv6j495y

**Comment by UPradeep** [comment]
Hi Guillaume,
    thanks for your quick reply. I tried v1 beta as you told but still i have issue when we do first scroll with child table and do second scroll with parent the child table is getting problem in fixed columns.


Thank you,
Pradeep.

**Comment by GuillaumeJasmin** [comment]
Hi Pradeep,
Please reproduce the bug on codesandbox. You can start from this example: https://codesandbox.io/s/jnjv6j495y
I started some improvement with fixed columns on sub components, but I need to see exactly your bug.

I never used fixed columns with sub component, only with pivot and aggregation, so I know that it not currently work well

**Comment by UPradeep** [comment]
Hi Guillaume,
    i added code on sandbox at https://codesandbox.io/s/z6zvl895yp .
Steps to reproduce:
1.Please do expand 'name' column on child table first and scroll that table.
2.Scroll parent table.


Thank you,
Pradeep.
