### ISSUE TITLE
Can ES7 requirement be mentioned in the README?

### ISSUE THREAD

**Issue by andrewnessinjim** [GuillaumeJasmin/react-table-hoc-fixed-columns#20]
`Array.prototype.includes` which is used by this project is [available from ES7 onward](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/includes). Wouldn't it be a good idea to mention that in the README?

I had to spend some time  (not more than 10mins) to figure this out and include the [es7-shim](https://www.npmjs.com/package/es7-shim) in my project.

**Comment by GuillaumeJasmin** [comment]
Hi,
Thanks for your feedback, and apologies for the lack of doc about ES7 features. I will added it in fews days in the README. Thanks !
