### ISSUE TITLE
Can not add custom class for Table component

### ISSUE THREAD

**Issue by 1silversnow1** [GuillaumeJasmin/react-table-hoc-fixed-columns#24]
When i'm trying to add class for Table component. Lib stops work properly. 
I did some research on sources and found this chunk of code:
`if (event.nativeEvent.target.getAttribute('class') !== 'rt-table') return;`
Would be better use something like this?
`if (!event.nativeEvent.target.getAttribute('class').includes('rt-table')) return;`
Or you have some specific reasons to do strict class checking?

**Comment by GuillaumeJasmin** [comment]
Hi,
Thanks for your feedback !
There is no specific reason, it’s a bug. Your proposal is good !
You can make a PR or I will fix it in few days, surely monday

**Comment by GuillaumeJasmin** [comment]
It's fixed on `v1.0.7` and `v2.0.0-beta.6`
