### ISSUE TITLE
Update innerRef type

### ISSUE THREAD

**Issue by ivanbtrujillo** [GuillaumeJasmin/react-table-hoc-fixed-columns#26]
Hi @GuillaumeJasmin ,

First of all, thanks for this amazing HOC.

The reason of this issue is that I think you should update the innerRef type to allow pass an object, due to React.createRef() API introduced in React 16.3, which generates an immutable object which we can pass as reference.

If I pass a React.createRef() object, it works without problem but gives a warning due the type:

![image](https://user-images.githubusercontent.com/6088653/52918598-caf36780-32f0-11e9-925e-fbf9d18a8241.png)

So the update must be change the type in order to supress the warning:

From:
```
innerRef: PropTypes.func
```
To:
```
innerRef: PropTypes.oneOfType([
  PropTypes.func,
  PropTypes.object
]
```
Thanks!

**Comment by GuillaumeJasmin** [comment]
Hi @ivanbtrujillo 
Thanks for your feedback!

It's fixed on `v1.0.7` and `v2.0.0-beta.6`
