### ISSUE TITLE
Broken cell widths after resizing

### ISSUE THREAD

**Issue by MartinYW** [GuillaumeJasmin/react-table-hoc-fixed-columns#28]
When group headers are not presented after resizing a column all widths of cells broke.

https://codesandbox.io/s/n7l6l5j3n0

Tested in last versions of Safari, Chrome and Firefox and everywhere it's broken.

**Comment by GuillaumeJasmin** [comment]
Hi Martin,
Thanks for your feedback. I see that bug, but it's not an issue with this HOC, but with react-table@6.9.0 .

See that without HOC: https://codesandbox.io/s/8436q87p0l

This bug doesn't appear with react-table@6.8.6

**Comment by GuillaumeJasmin** [comment]
This bug is already reported on react table repo: https://github.com/tannerlinsley/react-table/issues/1272

**Comment by MartinYW** [comment]
Oh yeah, thank you for review!
