### ISSUE TITLE
sticky column issue

### ISSUE THREAD

**Issue by followflydge** [GuillaumeJasmin/react-table-hoc-fixed-columns#3]
Hello @GuillaumeJasmin ,
i'm facing with a new issue.

How to get the problem, like in the img: ![image](https://user-images.githubusercontent.com/36823884/42376466-ea10fd24-8127-11e8-8d15-4b9f6e7e4b1f.png)

- you need to have several columns for horizontal scrolling:
- scroll to the right
- narrow down multiple columns

**Comment by GuillaumeJasmin** [comment]
Hi,

I try but I was not able to reproduce your bug

I currently work on a `v1`, it's now in beta. You can install it via the tag `next`. Maybe the next version will fix your issue ? 

Release note here: https://github.com/GuillaumeJasmin/react-table-hoc-fixed-columns/releases/tag/v1.0.0-beta.3

Docs here: https://github.com/GuillaumeJasmin/react-table-hoc-fixed-columns/tree/next

Demo here: https://codesandbox.io/s/jnjv6j495y

**Comment by followflydge** [comment]
TY for a very fast reply!!!
in the new version everything works fine.
GJ :+1:
