### ISSUE TITLE
React hooks version!

### ISSUE THREAD

**Issue by MrChe** [GuillaumeJasmin/react-table-hoc-fixed-columns#31]
Hi. Excellent  library . Maybe you create react hooks version in future?

**Comment by GuillaumeJasmin** [comment]
Hi,
I don't see why react hooks could be useful with `react-table-hoc-fixed-columns` ?
react-table v7 is currently in development state with hooks support.

Could you give me an example of `react-table-hoc-fixed-columns` usage with hooks ?

**Comment by hansena** [comment]
@GuillaumeJasmin is he trying to ask if this library will be compatible w/ react-table v7?

**Comment by wordythebyrd** [comment]
I am also curious if this library will be compatible with react-table v7.

**Comment by GuillaumeJasmin** [comment]
No, this HOC won't be compatible with react-table v7 because it's completely different and RT v7 will handle fixed columns natively

**Comment by GuillaumeJasmin** [comment]
I started a sticky hook for v7: https://github.com/GuillaumeJasmin/react-table-sticky

It's still unstable as `react-table@7.x.x` is in RC state, but you can use it with fixed version

**Comment by wordythebyrd** [comment]
Sweet!

I recently implemented my own sticky header and columns with RT 7, but with CSS only.  I followed [this guide](https://stackoverflow.com/a/50516259).

I'll check this out when I get a chance, I remember the hoc for RT 6.x having additional support for IE11 fallback.

**Comment by GuillaumeJasmin** [comment]
Your guide link is very similar with what I have implemented in `react-table-sticky`, it's full CSS with only some more things:
- the left / right value own by `react-table` when we have multiple sticky column
- some css attrs for custom style like border or box-shadow for first / last sticky column
