### ISSUE TITLE
Jest test cases are failing due to issue in dependent dependency.

### ISSUE THREAD

**Issue by nagendratank** [GuillaumeJasmin/react-table-hoc-fixed-columns#35]
When running unit test cases all the test case are failing due to react-table-hoc-fixed-columns using uniqid component and there is on going issue https://github.com/adamhalasz/uniqid/issues/23 which is failing the same for us as well.

 `
 ReferenceError: interface_key is not defined

      at Object.<anonymous> (node_modules/uniqid/index.js:21:10)
      at Object.<anonymous> (node_modules/react-table-hoc-fixed-columns/lib/stickyPosition/index.js:12:38)
      at Object.<anonymous> (node_modules/react-table-hoc-fixed-columns/lib/index.js:22:46)
      at Object.<anonymous> 
`

**Comment by GuillaumeJasmin** [comment]
So it's not an issue with `react-table-hoc-fixed-columns` but with `uniqid`.
A work around is to avoid to use `uniqid` by prodiving `uniqClassName` props:
https://github.com/GuillaumeJasmin/react-table-hoc-fixed-columns/blob/9c2691de2d5b916328cb94a09b787a80cf273133/src/lib/stickyPosition/index.js#L30

**Comment by GuillaumeJasmin** [comment]
I think I will remove `uniqid` in the future
