### ISSUE TITLE
FixedHeader not work when without uniqClassName prop on ssr

### ISSUE THREAD

**Issue by ycscholes** [GuillaumeJasmin/react-table-hoc-fixed-columns#36]
Hi, I found if without uniqClassName prop on ssr, following warning appears
`Warning: Prop `className` did not match. Server: "ReactTable rthfc-5eb8ct1u9ljxd1j1kf rthfc -sp" Client: "ReactTable rthfc-jxd1j237 rthfc -sp"`
and fixed header not work, after i read source code and add add uniqClassName prop, it works fine.

Could you write it on document or fixed it, thank you

**Comment by GuillaumeJasmin** [comment]
Where do you want I add uniqClassName prop ? It already exist so I don’t understand what you want. Show me an example please ?

**Comment by ycscholes** [comment]
Sorry, I cannot find a way to show an online demo for SSR(next.js), here is a screenshot for warning
![image](https://user-images.githubusercontent.com/8519563/60588272-10f52780-9dc9-11e9-9616-a3e04447b7d6.png)

If I add uniqClassName, the warning disappear. 
Hope it helps.

Thanks

**Comment by GuillaumeJasmin** [comment]
So what is the problem ? You found your solution: add a uniqClassName.
uniqClassName props is made for that. The default value is a uniqid(), but you can choose your own uniqClassName.
