### ISSUE TITLE
getTrProps does not work 

### ISSUE THREAD

**Issue by alexanderwhatley** [GuillaumeJasmin/react-table-hoc-fixed-columns#37]
See the following example: https://codesandbox.io/s/react-table-gettrprops-c54nb. When I remove the getTrProps function, everything works correctly, but if I add it, everything disappears.

**Comment by GuillaumeJasmin** [comment]
Everything doesn't disappears, but you set a white color to your text, so it's invisible.
Remove your color:
```
style: {
  ...
  color: "white"
}
```

**Comment by trivektor** [comment]
@GuillaumeJasmin actually the problem here is that after removing the color, the background of the rows where age > 20 are not red. `getTrProps` is not working

**Comment by trivektor** [comment]
@GuillaumeJasmin @alexanderwhatley let me take that back. `getTrProps` is actually working. The reason the background of each row doesn't appear is because the cells have a white background 

https://github.com/GuillaumeJasmin/react-table-hoc-fixed-columns/blob/master/src/lib/styles.css#L10-L13
