### ISSUE TITLE
header broken when multiple tables on the same page

### ISSUE THREAD

**Issue by eugenenelou** [GuillaumeJasmin/react-table-hoc-fixed-columns#40]
With multiple tables on the same page, `updateRowsPosition`  add offsets to consecutive header rows by their index in the page, not in their table. So the first header row of the second table has an offset but it should not.

**Comment by GuillaumeJasmin** [comment]
Hi @eugenenelou , thanks for your feedback !
Do you use the same `uniqClassName` props for both tables ? If yes, your issue come from that.
The default value of `uniqClassName` is `uniqid()`, but if you provide your own `uniqClassName`, it must be unique for each table. Let me know if that fix your issue

**Comment by eugenenelou** [comment]
@GuillaumeJasmin thank you, yes that fixes it. I'll need to search why we fixed the className in the first place.
