### ISSUE TITLE
I am getting list of error in console. 

### ISSUE THREAD

**Issue by Nekores** [GuillaumeJasmin/react-table-hoc-fixed-columns#51]
I have followed the installation guide and it is working with 20 errors in console. 
Here i have list few of them:

1. Warning: Failed prop type: ReactTable: prop type `TableComponent` is invalid; it must be a function, usually from the `prop-types` package, but received `undefined`.
2. Warning: Failed prop type: ReactTable: prop type `TheadComponent` is invalid; it must be a function, usually from the `prop-types` package, but received `undefined`.
3. Warning: Failed prop type: ReactTable: prop type `TbodyComponent` is invalid; it must be a function, usually from the `prop-types` package, but received `undefined`.
.
.
.
20. Warning: Failed prop type: ReactTable: prop type `TheadComponent` is invalid; it must be a function, usually from the `prop-types` package, but received `undefined`.

Let me know, how to get rid of those errors. For more i have attached the screenshot. Thanks
<img width="1870" alt="Screenshot 2019-11-08 at 6 24 07 AM" src="https://user-images.githubusercontent.com/20630025/68441574-649cd500-01f0-11ea-9c4f-4cb4abf03289.png">

**Comment by GuillaumeJasmin** [comment]
Have you try without fixed columns ?
It's not a problem with react-table-hoc-fixed-column because it doesn't use `TableComponent` or `TheadComponent` .
Have you install `prop-types` package ?

**Comment by Nekores** [comment]
Thanks for the response.
Well, actually I am working for a client. They have initially setup the project, so I am working with their flow. Yes, `prop-types` is installed and this package is mandatory.
I didn't tried it without **fixed columns**

**Comment by GuillaumeJasmin** [comment]
Please specify which version of `react-table` and `react-table-hoc-fixed-columns` you have.
Try without fixed columns and see if you still have the problem then it's not an issue with fixed columns.

**Comment by GuillaumeJasmin** [comment]
I confirm that issue doesn't come from `fixed-columns`
