### ISSUE TITLE
Cannot read property 'column' of undefined

### ISSUE THREAD

**Issue by vamsi466** [GuillaumeJasmin/react-table-hoc-fixed-columns#52]
I had installed the react-table & react-table-hoc-fixed-columns but it is unable to pass this line. Unable to get the index.js file or index.d.ts (declaration file) 

import withFixedColumns from 'react-table-hoc-fixed-columns';
const ReactTableFixedColumns = withFixedColumns(ReactTable);

It is throwing if I keep this line of CSS of react-table 
import "react-table/react-table.css";
![issue](https://user-images.githubusercontent.com/23494398/70056055-cfc7a480-1600-11ea-87e3-ded5b9680b32.JPG)

**Comment by GuillaumeJasmin** [comment]
Hi,
What version of react-table do you have ?

**Comment by vamsi466** [comment]
React-table 7.0.0 version
react-table-hoc-fixed-columns - 2.1.2

**Comment by GuillaumeJasmin** [comment]
`react-table-hoc-fixed-columns` is not compatible with v7, it's only for v6.
v7 is a new architecture build with React hooks

**Comment by vamsi466** [comment]
Thank you so much for the quick response.
This is a small doubt is it possible for rendering the column headers dynamically from API response instead of static ones

**Comment by GuillaumeJasmin** [comment]
For pinned colums in v7, it will be included into the core package `react-table`. Feature request is still open: https://github.com/tannerlinsley/react-table/issues/1509

Yes of course, I did it that in many tables I built. You have to build your `columns` props with you API data

**Comment by vamsi466** [comment]
Okay, thank you

**Comment by GuillaumeJasmin** [comment]
I started a sticky hook for v7: https://github.com/GuillaumeJasmin/react-table-sticky

It's still unstable as react-table@7.x.x is in RC state, but you can try it with fixed version
