### ISSUE TITLE
HOC broken by react-table issue #1686

### ISSUE THREAD

**Issue by joshsylvester** [GuillaumeJasmin/react-table-hoc-fixed-columns#54]
Unfortunately, the `react-table` team released a breaking change `@latest` which is causing any builds that include `react-table-hoc-fixed-columns` to completely fail.

would it be possible to update your `package.json` to reference a known working version of `react-table` until the upgrade to `v7` can be completed?

`npm install --save react-table@6.10.0`

**Comment by GuillaumeJasmin** [comment]
You want `react-table@6.10.0` as a peerDependencies in package.json ?

**Comment by joshsylvester** [comment]
That would be my suggestion, as a stopgap which would allow your package continue to work - that is, until the issue that was introduced by the `react-table` team can be fixed properly.

https://github.com/tannerlinsley/react-table/issues/1686

**Comment by GuillaumeJasmin** [comment]
I don't understand. If there is a breaking change that is completely independent of `react-table-hoc-fixed-columns`, why specify a working version ?
If react-table without react-table-hoc-fixed-columns is broken, there is no link with this HOC ?

**Comment by GuillaumeJasmin** [comment]
"any builds that include react-table-hoc-fixed-columns to completely fail"
It's that I don't understand. Any build with react-table will fail too, even without fixed-columns? fixed-columns can't work alone

**Comment by joshsylvester** [comment]
my apologies, I may have overstepped the situation. Let me finalize my tests and get back to you.

**Comment by joshsylvester** [comment]
It looks like the `react-table` team just released a new build (which we're using), but we're still getting a failure when building for production - still looking into the cause.
```
Can't resolve 'react-table' in '/.../node_modules/react-table-hoc-fixed-columns/lib/scrollEvent
```

**Comment by GuillaumeJasmin** [comment]
I just update the codesandbox demo with latest v6 `react-table@6.11.4` and it works

https://codesandbox.io/s/kowzlm5jp7

**Comment by GuillaumeJasmin** [comment]
@joshsylvester do you still have issue with latest `react-table-hoc-fixed-columns` ?

**Comment by joesalloum** [comment]
@joshsylvester i still have an issue on build using react-table 6.7.5 and react-table-hoc-fixed-columns 2.1.3

on development it's working fine but on build having problem i think with uglify any fix for it ???

**Comment by joshsylvester** [comment]
@joesalloum I'm not sure about uglify - Once I updated to `react-table@6.11.4` everything went back to normal. as far as this ticket is concerned - this can be closed for the existing version. I'm still hopeful that something can be done to get this to work with `react-table@7.0.0` once it's fully release, though i realize changes on their side may still be needed.

**Comment by GuillaumeJasmin** [comment]
@joshsylvester I start a sticky version for v7 https://github.com/GuillaumeJasmin/react-table-sticky
