### ISSUE TITLE
The current implementation of creates new column instance on every render

### ISSUE THREAD

**Issue by shri1897** [GuillaumeJasmin/react-table-hoc-fixed-columns#55]
The current implementation of creates new column instance on every render which causes performance issues

**Comment by GuillaumeJasmin** [comment]
Feel free to open a PR with better implementation

**Comment by shri1897** [comment]
> Feel free to open a PR with better implementation

https://github.com/GuillaumeJasmin/react-table-hoc-fixed-columns/pull/56 
Please review this PR

**Comment by shri1897** [comment]
Thanks :)

**Comment by provish** [comment]
Nice.
