### ISSUE TITLE
build error

### ISSUE THREAD

**Issue by joesalloum** [GuillaumeJasmin/react-table-hoc-fixed-columns#57]
Dear @GuillaumeJasmin  thank you for this amazing hoc component, it's really helpful

in development it's working properly but i'm facing a problem on build,

Failed to compile.
static/js/main.1b0ccaee.js from UglifyJs
SyntaxError: Unexpected token name «interface_key», expected punc «;» [./~/uniqid/index.js:18,0]

please i need help to fix this problem

thanks in advance

**Comment by GuillaumeJasmin** [comment]
Hi,
It seems to be a problem with your Uglify process, it doesn't accept ES6 syntax.
This issue come from uniqid lib, not fixed-columns

**Comment by joesalloum** [comment]
@GuillaumeJasmin yes i noticed the message but before using your component it was working perfect
when i implemented the component it didn't let me do a production version and gave me this error
was hoping you had a fix it

**Comment by GuillaumeJasmin** [comment]
Yes because my component use uniqid lib, but the issue is not in fixed-columns lib.
The solution is to allow your build process to understand ES6 syntax.
What do you use ?

**Comment by GuillaumeJasmin** [comment]
@joesalloum do you have fixed your issue ?

**Comment by naisargparmar** [comment]
@GuillaumeJasmin @joesalloum can you please provide solution for this?

**Comment by joesalloum** [comment]
@naisargparmar honestly not sure if i did fix it or not and the project isn't with me anymore to check sorry
