### ISSUE TITLE
`fixed: left` with 2 columns fails in v2+

### ISSUE THREAD

**Issue by markwoon** [GuillaumeJasmin/react-table-hoc-fixed-columns#59]
After migrating from 1.x to 2.x I noticed that `fixed: left` with more than one column is broken.

This is what I expected: 

![good](https://user-images.githubusercontent.com/215141/75400470-37198b80-58b4-11ea-9078-b5a09b2bf38f.png)

This is what I got (notice the column title `Variant` gets pushed over to the next column):

![bad](https://user-images.githubusercontent.com/215141/75400479-40a2f380-58b4-11ea-911b-16ef60617558.png)

Until I figure out a way to patch this and get `react-table` and `react-table-6` to co-exist, you can see this problem at https://www.pharmgkb.org/chemical/PA10026/variantAnnotation 

Deleting line 136 and 151 in `stickyPosition/index.js` seems to fix the problem for me.

If this issue can't be resolved in a timely manner, would you be able to release a version of 1.x with the fix for #58?

Thanks.

**Comment by GuillaumeJasmin** [comment]
Hi,
Thanks for your feedback !
Can you reproduce your issue with code sandbox example ? I think it’s just a config issue in your columns props. Or just copy/past your config here

V1 should works with react-table-v6 because #58 only exist on v2, because I used react-table dependency on v2 but not on v1. Have you try v1 and react-table-v6 together ?

**Comment by markwoon** [comment]
You're right, v1 works just fine.  I should have checked myself.

Here's a quick and dirty example: https://codesandbox.io/s/awesome-bogdan-8rp83?fontsize=14&hidenavigation=1&theme=dark

I think this might just be a duplicate of #27.

**Comment by GuillaumeJasmin** [comment]
You have to import styles of `fixed-columns` after styles of react-table, like this:

```
import "react-table-6/react-table.css";
import "react-table-hoc-fixed-columns/lib/styles.css";
```

That will fix your UI issue.

Also, in your example, all your columns are `fixed: "left"` which is useless ? remove `fixed` on lastname and that works

**Comment by markwoon** [comment]
Whoops.  Looks like I didn't spend enough time working up that example.  You're right, those changes worked.  I'll try and see if I can port over my table to codesandbox but it's not a priority right now as I've just downgraded to 1.0.7.  Feel free to close this issue.
