### ISSUE TITLE
fixed columns cant scrolled

### ISSUE THREAD

**Issue by indrakurniawaw** [GuillaumeJasmin/react-table-hoc-fixed-columns#60]
i has installed the library few months ago and it worked fine. but when i opened my project last week until today the table cant worked. the column cant scrolled anymore

**Comment by indrakurniawaw** [comment]
https://codesandbox.io/s/recursing-yonath-5xxb4

**Comment by GuillaumeJasmin** [comment]
Hi @indrakurniawaw 
You codesandbox is broken. Have you still an issue with the scroll ?
