### ISSUE TITLE
Add type of innerRef prop to the index.d.ts file

### ISSUE THREAD

**Issue by TiagoPortfolio** [GuillaumeJasmin/react-table-hoc-fixed-columns#61]
When using TypeScript, I noticed that the `innerRef` prop type is missing in the _index.d.ts_ file.
Is it possible to add its type anytime soon?

Cheers!

**Comment by GuillaumeJasmin** [comment]
Hi @TiagoPortfolio 
Thanks for your feedback ! Oh yes, it's a mistake, I will add it soon

**Comment by jakubarendac** [comment]
Hi @GuillaumeJasmin, 
is there any update on this issue ? 

thanks

**Comment by GuillaumeJasmin** [comment]
fixed on `v2.3.1`
