### ISSUE TITLE
Bugs with react-table v7.1.0

### ISSUE THREAD

**Issue by nguyenvannghi** [GuillaumeJasmin/react-table-hoc-fixed-columns#62]
I have a problem with react v7.1.0: **`Cannot read property 'defaultProps' of undefined`**

[Link](https://codesandbox.io/s/react-table-fixed-columns-official-bcu1q)

**Comment by GuillaumeJasmin** [comment]
`react-table-hoc-fixed-columns` is for v6.
For v7, you can use [react-table-sticky](https://github.com/GuillaumeJasmin/react-table-sticky)
