### ISSUE TITLE
fixed column resize bug

### ISSUE THREAD

**Issue by vtarelkin** [GuillaumeJasmin/react-table-hoc-fixed-columns#65]
https://codesandbox.io/s/kowzlm5jp7?file=/index.js:281-310

please resize first column to the left to make it small
scroll left and right over the middle part of the table and view the middle part appears on the left fixed side of the table

**Comment by CRGavrila** [comment]
In this "left" prop style of second column should increase/decrease with width of first column.
In general, "left" prop style for fixed columns after the resized column should increase/decrease with the difference of (initial width - final width)

**Comment by vtarelkin** [comment]
any quick fix?)

**Comment by CRGavrila** [comment]
something like this

**Comment by vtarelkin** [comment]
> something like this: #66

@CRGavrila I use react-table v6, I don't use memo. What should I change?

**Comment by vtarelkin** [comment]
@CRGavrila please, take a quick look ;-)

**Comment by GuillaumeJasmin** [comment]
Hi !
Thanks for your feedback and PR.
I will check it in detail very soon

**Comment by vtarelkin** [comment]
@GuillaumeJasmin I check it every day)

**Comment by GuillaumeJasmin** [comment]
fixed as of `v2.3.2`

**Comment by vtarelkin** [comment]
@GuillaumeJasmin @CRGavrila excellent, thank you!
